[package]
name = "rust-closures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros", "full"] }
forceps = "0.4.1"
mhdb = "1.0.3"

